### ISSUE TITLE
New bulletin items not displaying / stale data

### ISSUE THREAD

**Issue by unbracketed** [bensbits91/nextjs-music-scene#12]
Newly posted items aren't displaying, even after refreshes.   It looks like the SWR hook maybe fails the network request for some reason and then serves stale data.  I didn't look closely but it didn't look like each browser refresh was causing a hit to the API

**Comment by bensbits91** [comment]
It works in my dev environment (I think I've said that before). Related to issue #6. I'll take a look...

**Comment by unbracketed** [comment]
I think I'm starting to understand what's happening.  It works locally because the next dev server calls `getStaticProps` each request.  It looks like there might be some steps left to the reader for how to make SWR work client-side in a Next.js Page component AFAICT?  Alternatively, might need to set the site up differently at Netlify to support SSR (OK), or move the site to Vercel (also OK).
